### ISSUE TITLE
Export texture data support

### ISSUE THREAD

**Issue by ghost** [zhenghuadai/webcs#3]
I needs to export texture data into image (PNG). Needs `getData` implement for texture. And preserve channels, include alpha channel. And in general, in practice, mostly, not working. Not working uniforms. And not working passing typed arrays.

**Comment by zhenghuadai** [comment]
1. Update the webcs for pass typed array besides Float32Array.
2. Add save_texture example.  I don't have a direct method for getData from texture,  currently the texture is drawn to canvas, then get data by canvas.toDataURL
